### ISSUE TITLE
RollupError: @rollup/plugin-typescript: Could not find module 'tslib', which is required by this plugin. Is it installed?

### ISSUE THREAD

**Issue by SvenWangChina** [photonstorm/phaser3-typescript-project-template#27]
I run the project on my macOS.
First run `npm install`, and then `npm run dev`, got follow error:

    ./src/game.ts → ./dist/game.js...
    [!] (plugin typescript) RollupError: @rollup/plugin-typescript: Could not find module 'tslib', which is required by this plugin. Is it installed?
    at error (/Users/sven/Documents/Crowdsourcing/phaser3-typescript-project-template-master/node_modules/rollup/dist/shared/rollup.js:274:30)
    at Object.error (/Users/sven/Documents/Crowdsourcing/phaser3-typescript-project-template-master/node_modules/rollup/dist/shared/rollup.js:24694:20)
    at preflight (file:///Users/sven/Documents/Crowdsourcing/phaser3-typescript-project-template-master/node_modules/@rollup/plugin-typescript/dist/es/index.js:496:17)
    at Object.buildStart (file:///Users/sven/Documents/Crowdsourcing/phaser3-typescript-project-template-master/node_modules/@rollup/plugin-typescript/dist/es/index.js:746:13)
    at /Users/sven/Documents/Crowdsourcing/phaser3-typescript-project-template-master/node_modules/rollup/dist/shared/rollup.js:24893:40
    at async Promise.all (index 3)
    at PluginDriver.hookParallel (/Users/sven/Documents/Crowdsourcing/phaser3-typescript-project-template-master/node_modules/rollup/dist/shared/rollup.js:24821:9)
    at /Users/sven/Documents/Crowdsourcing/phaser3-typescript-project-template-master/node_modules/rollup/dist/shared/rollup.js:26005:13
    at catchUnfinishedHookActions (/Users/sven/Documents/Crowdsourcing/phaser3-typescript-project-template-master/node_modules/rollup/dist/shared/rollup.js:25256:20)
    at rollupInternal (/Users/sven/Documents/Crowdsourcing/phaser3-typescript-project-template-master/node_modules/rollup/dist/shared/rollup.js:26002:5)

**Comment by photonstorm** [comment]
Add it via `npm i tslib`
